; Assembly language version of FizzBuzz problem generated by ChatGTP3
; Set the counter to 1
mov ecx, 1

; Iterate through the numbers 1 to 100
fizzbuzz_loop:
    ; Check if the number is divisible by both 3 and 5
mov eax, ecx
xor edx, edx
div 3
cmp edx, 0
jne not_fizz
mov eax, ecx
xor edx, edx
div 5
cmp edx, 0
jne not_fizzbuzz

; If the number is divisible by 3 and 5, print "FizzBuzz"
push 0x00756275
push 0x657A6946
mov ebx, esp
mov eax, 4
mov ecx, ebx
mov edx, 10
int 0x80
jmp next

not_fizzbuzz:
    ; Check if the number is divisible by 3
mov eax, ecx
xor edx, edx
div 3
cmp edx, 0
jne not_fizz

; If the number is divisible by 3, print "Fizz"
push 0x007A6946
mov ebx, esp
mov eax, 4
mov ecx, ebx
mov edx, 4
int 0x80
jmp next

not_fizz:
    ; Check if the number is divisible by 5
mov eax, ecx
xor edx, edx
div 5
cmp edx, 0
jne not_fizzbuzz_or_fizz

; If the number is divisible by 5, print "Buzz"
push 0x00756275
mov ebx, esp
mov eax, 4
mov ecx, ebx
mov edx, 4
int 0x80
jmp next

not_fizzbuzz_or_fizz:
    ; Otherwise, print the number
mov ebx, ecx
mov eax, 1
mov ecx, ebx
mov edx, 1
int 0x80

next:
    ; Increment the counter and repeat the loop
inc ecx
cmp ecx, 101
jne fizzbuzz_loop
